### ISSUE TITLE
A página index.html sugere usar DuckDuckGo mas o hash obtido não coincide com outras ferramentas.

### ISSUE THREAD

**Issue by horaciohs** [cuducos/pwned-antifas#13]
No DuckDuckGo calculando o hash sha-512 da string "João da Silva" resulta:
fab687418ca251d4cfb079de71d44200ef56d637982b56d2df2d1f78ffc6106f8a2fee050f9c1e0b359e618ba890ef0d0e0b3e428186d95077d185b23a32ecd9

No Linux:
$ echo -n 'João da Silva' | sha512sum
d2975f13e399daa60bef015d3264fc2cb4368793d4e09ae889e86dd36960e24c7fd73018499b4197a45f275ad2b903fa3293a9460696bc3227a5fff7ca0c50e7  -

No site https://md5calc.com/hash/sha512/João+da+Silva obtenho o mesmo resultado do Linux.

1) Dependendo do método usado no script pwned-antifas parece-me que o hash gerado por eventuais usuários pode nunca coincidir com o da base de dados, gerando sempre falso-negativo.

2) Como o DuckDuckGo trata a string para calcular o seu hash ?

**Comment by earaujoassis** [comment]
Isso tem a ver com o encoding, o que já foi tratado no código, pelo que vi. Se você colocar a string "Joao", plain ASCII, por exemplo, sempre irá gerar o mesmo hash.

- https://md5calc.com/hash/sha512/Joao
- https://duckduckgo.com/?q=sha-512+Joao&t=hk&ia=answer
```sh
$ echo -n 'Joao' | shasum -a 512
```

b52ab2c28cdf83da93fee10cfcb6eaa7e3cecbb9c7d9e9f8dc6e7b44d09881d17b0ee2087c047bd14f235de2283951bdab0a3eea41d9e46741ebbc688a88baae
